import { addDays } from "@/features/applications/date-utils";
import type { EssayLibraryItem } from "@/features/essays/types";

const today = new Date();

/** 화면 확인용 예시 데이터. 실제 개인정보나 자격번호는 포함하지 않는다. */
export const essayLibraryMockData: EssayLibraryItem[] = [
  {
    answerId: "answer-kb-1",
    questionId: "question-kb-1",
    applicationId: "app-kb-2026-it",
    companyName: "KB국민은행",
    positionName: "IT 개발",
    recruitmentYear: 2026,
    season: "하반기",
    questionText: "당사를 선택한 기준과 지원 동기를 기술하시오.",
    commonQuestionType: "지원동기",
    experienceTags: ["LOODI"],
    competencyTags: ["문제 해결", "사용자 관점"],
    answerStatus: "작성본",
    version: 3,
    contentPreview:
      "금융 서비스는 한 번의 오류가 사용자의 하루를 무너뜨린다고 생각합니다. LOODI를 운영하며 결제 흐름에서 발생한 중복 요청을 직접 추적했던 경험이 있습니다. 안정적인 시스템이 곧 신뢰라는 점을 배웠고, 그 기준을 은행 시스템에서 이어가고 싶습니다.",
    characterCount: 842,
    characterLimit: 1000,
    submittedAt: null,
    updatedAt: addDays(today, -1),
  },
  {
    answerId: "answer-kb-2",
    questionId: "question-kb-2",
    applicationId: "app-kb-2026-it",
    companyName: "KB국민은행",
    positionName: "IT 개발",
    recruitmentYear: 2026,
    season: "하반기",
    questionText: "가장 어려웠던 문제를 해결한 경험을 서술하시오.",
    commonQuestionType: "문제해결",
    experienceTags: ["LOODI", "씨앤태크 ICT 인턴"],
    competencyTags: ["문제 해결", "안정성"],
    answerStatus: "작성본",
    version: 2,
    contentPreview:
      "동시 요청이 몰릴 때만 재현되는 데이터 정합성 문제가 있었습니다. 로그만으로는 원인을 좁히지 못해 요청 순서를 기록하는 임시 추적 코드를 넣었습니다. 결국 트랜잭션 경계가 잘못 잡힌 지점을 찾아 수정했고 이후 동일 오류는 재발하지 않았습니다.",
    characterCount: 918,
    characterLimit: 1000,
    submittedAt: null,
    updatedAt: addDays(today, -2),
  },
  {
    answerId: "answer-kb-3",
    questionId: "question-kb-3",
    applicationId: "app-kb-2026-it",
    companyName: "KB국민은행",
    positionName: "IT 개발",
    recruitmentYear: 2026,
    season: "하반기",
    questionText: "협업 과정에서 갈등을 조정한 경험을 기술하시오.",
    commonQuestionType: "협업갈등",
    experienceTags: ["기숙사 커뮤니티"],
    competencyTags: ["협업", "책임감"],
    answerStatus: "작성본",
    version: 1,
    contentPreview:
      "기숙사 커뮤니티 운영진 사이에서 공지 방식에 대한 의견이 갈렸습니다. 각자의 우선순위를 먼저 정리한 뒤 실제 이용자 설문으로 판단 기준을 옮겼습니다. 감정이 아니라 데이터로 합의한 경험이었습니다.",
    characterCount: 612,
    characterLimit: 800,
    submittedAt: null,
    updatedAt: addDays(today, -5),
  },
  {
    answerId: "answer-shinhan-1",
    questionId: "question-shinhan-1",
    applicationId: "app-shinhan-ict",
    companyName: "신한은행",
    positionName: "ICT",
    recruitmentYear: 2026,
    season: "하반기",
    questionText: "지원 분야를 선택한 이유와 준비 과정을 작성해 주세요.",
    commonQuestionType: "지원동기",
    experienceTags: ["씨앤태크 ICT 인턴"],
    competencyTags: ["안정성", "책임감"],
    answerStatus: "작성본",
    version: 1,
    contentPreview:
      "인턴 기간 동안 운영 중인 시스템의 장애 대응을 가까이에서 지켜봤습니다. 새로운 기능을 만드는 일보다 이미 돌아가는 시스템을 지키는 일이 더 어렵다는 것을 알게 되었습니다. ICT 직무에서 그 역할을 맡고 싶습니다.",
    characterCount: 534,
    characterLimit: 1000,
    submittedAt: null,
    updatedAt: addDays(today, -3),
  },
  {
    answerId: "answer-kakao-1",
    questionId: "question-kakao-1",
    applicationId: "app-kakao-backend",
    companyName: "카카오",
    positionName: "백엔드",
    recruitmentYear: 2026,
    season: "수시",
    questionText: "본인의 기술적 강점을 프로젝트 사례와 함께 설명해 주세요.",
    commonQuestionType: "직무역량",
    experienceTags: ["LOODI"],
    competencyTags: ["문제 해결", "안정성"],
    answerStatus: "제출본",
    version: 4,
    contentPreview:
      "서비스 초기에는 응답 속도보다 기능 추가가 우선이었습니다. 사용자가 늘면서 목록 조회가 느려졌고, 쿼리 실행 계획을 하나씩 확인하며 인덱스를 다시 설계했습니다. 평균 응답 시간을 절반 이하로 줄였습니다.",
    characterCount: 976,
    characterLimit: 1000,
    submittedAt: addDays(today, -12),
    updatedAt: addDays(today, -12),
  },
  {
    answerId: "answer-kakao-2",
    questionId: "question-kakao-2",
    applicationId: "app-kakao-backend",
    companyName: "카카오",
    positionName: "백엔드",
    recruitmentYear: 2026,
    season: "수시",
    questionText: "실패했던 경험과 그로부터 배운 점을 작성해 주세요.",
    commonQuestionType: "도전실패",
    experienceTags: ["LOODI", "성적우수자"],
    competencyTags: ["책임감", "사용자 관점"],
    answerStatus: "개선본",
    version: 5,
    contentPreview:
      "첫 배포에서 롤백 절차를 준비하지 않아 서비스가 30분간 중단되었습니다. 원인보다 복구가 늦었던 점이 더 뼈아팠습니다. 이후에는 배포 전 롤백 시나리오를 먼저 문서화하는 습관을 들였습니다.",
    characterCount: 887,
    characterLimit: 1000,
    submittedAt: addDays(today, -12),
    updatedAt: addDays(today, -6),
  },
  {
    answerId: "answer-naver-1",
    questionId: "question-naver-1",
    applicationId: "app-naver-platform",
    companyName: "네이버",
    positionName: "플랫폼 엔지니어",
    recruitmentYear: 2026,
    season: "상반기",
    questionText: "성장 과정에서 본인에게 가장 큰 영향을 준 경험은 무엇입니까?",
    commonQuestionType: "성장과정",
    experienceTags: ["군 최우수상"],
    competencyTags: ["책임감", "협업"],
    answerStatus: "제출본",
    version: 2,
    contentPreview:
      "군 복무 중 통신 장비 관리를 맡으면서 반복 점검의 가치를 배웠습니다. 눈에 띄지 않는 일이지만 빠뜨리면 전체가 멈추는 일이었습니다. 꾸준함이 성과로 이어질 수 있다는 것을 처음 체감했습니다.",
    characterCount: 723,
    characterLimit: 800,
    submittedAt: addDays(today, -40),
    updatedAt: addDays(today, -40),
  },
  {
    answerId: "answer-naver-2",
    questionId: "question-naver-2",
    applicationId: "app-naver-platform",
    companyName: "네이버",
    positionName: "플랫폼 엔지니어",
    recruitmentYear: 2026,
    season: "상반기",
    questionText: "입사 후 이루고 싶은 목표를 구체적으로 작성해 주세요.",
    commonQuestionType: "입사포부",
    experienceTags: ["LOODI"],
    competencyTags: ["사용자 관점"],
    answerStatus: "작성본",
    version: 1,
    contentPreview:
      "플랫폼은 사용하는 개발자가 첫 번째 사용자라고 생각합니다. 내부 도구의 사용성을 개선해 팀 전체의 반복 작업을 줄이는 일을 맡고 싶습니다.",
    characterCount: 418,
    characterLimit: 800,
    submittedAt: null,
    updatedAt: addDays(today, -8),
  },
  {
    answerId: "answer-line-1",
    questionId: "question-line-1",
    applicationId: "app-line-server",
    companyName: "라인플러스",
    positionName: "서버 개발",
    recruitmentYear: 2026,
    season: "수시",
    questionText: "팀에서 본인의 역할을 설명하고 기여한 바를 기술해 주세요.",
    commonQuestionType: "협업갈등",
    experienceTags: ["LOODI", "기숙사 커뮤니티"],
    competencyTags: ["협업", "문제 해결"],
    answerStatus: "제출본",
    version: 3,
    contentPreview:
      "일정이 밀릴 때마다 원인을 개인이 아닌 절차에서 찾으려 했습니다. 작업 단위를 잘게 쪼개고 매일 짧게 진행 상황을 공유하도록 제안했습니다. 마감 지연이 눈에 띄게 줄었습니다.",
    characterCount: 655,
    characterLimit: 700,
    submittedAt: addDays(today, -20),
    updatedAt: addDays(today, -20),
  },
  {
    answerId: "answer-toss-1",
    questionId: "question-toss-1",
    applicationId: "app-toss-core",
    companyName: "토스",
    positionName: "Core Banking 개발",
    recruitmentYear: 2026,
    season: "수시",
    questionText: "본인이 생각하는 좋은 금융 서비스의 조건은 무엇입니까?",
    commonQuestionType: "직무역량",
    experienceTags: ["씨앤태크 ICT 인턴", "LOODI"],
    competencyTags: ["안정성", "사용자 관점"],
    answerStatus: "개선본",
    version: 6,
    contentPreview:
      "좋은 금융 서비스는 사용자가 시스템의 존재를 의식하지 않는 상태라고 생각합니다. 화면이 화려한 것보다 실패하지 않는 것이 먼저입니다. 인턴 기간에 본 장애 대응 절차가 그 기준을 만들어 주었습니다.",
    characterCount: 1180,
    characterLimit: 1200,
    submittedAt: addDays(today, -15),
    updatedAt: addDays(today, -4),
  },
  {
    answerId: "answer-toss-2",
    questionId: "question-toss-2",
    applicationId: "app-toss-core",
    companyName: "토스",
    positionName: "Core Banking 개발",
    recruitmentYear: 2026,
    season: "수시",
    questionText: "원칙과 효율이 충돌했을 때 어떻게 판단하시겠습니까?",
    commonQuestionType: "윤리책임",
    experienceTags: ["씨앤태크 ICT 인턴"],
    competencyTags: ["책임감", "안정성"],
    answerStatus: "작성본",
    version: 1,
    contentPreview:
      "금융 도메인에서는 되돌릴 수 없는 작업이 많습니다. 빠른 처리보다 확인 절차를 지키는 편을 택하겠습니다. 다만 절차 자체가 병목이라면 절차를 고치자고 제안하겠습니다.",
    characterCount: 496,
    characterLimit: 800,
    submittedAt: null,
    updatedAt: addDays(today, -9),
  },
  {
    answerId: "answer-hyundai-1",
    questionId: "question-hyundai-1",
    applicationId: "app-hyundai-data",
    companyName: "현대오토에버",
    positionName: "데이터 플랫폼",
    recruitmentYear: 2026,
    season: "하반기",
    questionText: "지원 직무에 필요한 역량을 어떻게 준비했는지 기술하시오.",
    commonQuestionType: "직무역량",
    experienceTags: ["성적우수자", "LOODI"],
    competencyTags: ["문제 해결"],
    answerStatus: "작성본",
    version: 2,
    contentPreview:
      "데이터가 쌓이기만 하고 쓰이지 않는 상황을 여러 번 봤습니다. 수집보다 정의가 먼저라고 생각해 지표 기준부터 문서로 정리했습니다. 이후 같은 숫자를 두고 논쟁하는 일이 줄었습니다.",
    characterCount: 705,
    characterLimit: 1000,
    submittedAt: null,
    updatedAt: addDays(today, -7),
  },
  {
    answerId: "answer-coupang-1",
    questionId: "question-coupang-1",
    applicationId: "app-coupang-infra",
    companyName: "쿠팡",
    positionName: "인프라 개발",
    recruitmentYear: 2026,
    season: "상반기",
    questionText: "새로운 기술을 학습해 실제 문제에 적용한 사례를 작성해 주세요.",
    commonQuestionType: "문제해결",
    experienceTags: ["LOODI"],
    competencyTags: ["문제 해결", "안정성"],
    answerStatus: "제출본",
    version: 2,
    contentPreview:
      "배포마다 수작업이 반복되어 실수가 잦았습니다. 컨테이너와 배포 스크립트를 처음부터 학습해 자동화 흐름을 만들었습니다. 배포 시간이 줄었을 뿐 아니라 실수 자체가 사라졌습니다.",
    characterCount: 834,
    characterLimit: 1000,
    submittedAt: addDays(today, -33),
    updatedAt: addDays(today, -33),
  },
  {
    answerId: "answer-woowa-1",
    questionId: "question-woowa-1",
    applicationId: "app-woowa-2025-server",
    companyName: "우아한형제들",
    positionName: "서버 개발",
    recruitmentYear: 2025,
    season: "하반기",
    questionText: "지원 동기와 본인이 회사에 기여할 수 있는 점을 작성해 주세요.",
    commonQuestionType: "지원동기",
    experienceTags: ["기숙사 커뮤니티"],
    competencyTags: ["협업", "사용자 관점"],
    answerStatus: "제출본",
    version: 1,
    contentPreview:
      "사용자가 남긴 불편을 기능으로 옮기는 과정을 좋아합니다. 커뮤니티를 운영하며 요청을 정리하고 우선순위를 정하는 일을 반복했습니다. 그 감각을 서비스 개발에서 쓰고 싶습니다.",
    characterCount: 588,
    characterLimit: 700,
    submittedAt: addDays(today, -300),
    updatedAt: addDays(today, -300),
  },
  {
    answerId: "answer-ncsoft-1",
    questionId: "question-ncsoft-1",
    applicationId: "app-ncsoft-2025-platform",
    companyName: "엔씨소프트",
    positionName: "플랫폼 개발",
    recruitmentYear: 2025,
    season: "상반기",
    questionText: "지금까지 가장 몰입했던 경험을 소개해 주세요.",
    commonQuestionType: "성장과정",
    experienceTags: ["군 최우수상", "성적우수자"],
    competencyTags: ["책임감"],
    answerStatus: "제출본",
    version: 1,
    contentPreview:
      "한 학기 동안 매주 같은 시간에 스터디를 운영했습니다. 인원이 줄어도 기록을 남기는 일은 멈추지 않았습니다. 결과보다 지속이 어렵다는 것을 배운 시간이었습니다.",
    characterCount: 472,
    characterLimit: 600,
    submittedAt: addDays(today, -420),
    updatedAt: addDays(today, -420),
  },
];
