import { describe, expect, it } from "vitest";
import {
  APPLICATION_KANBAN_COLUMNS,
  groupApplicationsByStatus,
  toNextScheduleByApplicationId,
} from "@/features/applications/kanban-utils";
import { toApplicationStatusViewModel } from "@/features/applications/api/mapper";
import type { ApplicationStatusDto } from "@/features/applications/api/dto";
import type { ApplicationListItem, ApplicationStatus } from "@/features/applications/types";
import type { CalendarEvent, CalendarEventType } from "@/features/calendar/types";

const BACKEND_STATUSES: ApplicationStatusDto[] = [
  "INTERESTED",
  "WRITING",
  "SUBMITTED",
  "DOCUMENT_RESULT",
  "TEST",
  "INTERVIEW",
  "FINAL_ACCEPTED",
  "FINAL_REJECTED",
];

function makeApplication(
  id: string,
  status: ApplicationStatus,
  overrides: Partial<ApplicationListItem> = {},
): ApplicationListItem {
  return {
    id,
    companyName: `회사 ${id}`,
    position: "IT 개발",
    recruitmentYear: 2026,
    season: "하반기",
    deadline: new Date("2026-09-14T09:00:00Z"),
    status,
    progress: 30,
    createdAt: new Date("2026-08-01T00:00:00Z"),
    ...overrides,
  };
}

function makeEvent(
  applicationId: string | null,
  eventType: CalendarEventType,
  startAt: string,
): CalendarEvent {
  return {
    id: `${applicationId}-${eventType}-${startAt}`,
    applicationId,
    companyName: "회사",
    positionName: "IT 개발",
    eventType,
    sourceType: applicationId ? "APPLICATION" : "MANUAL",
    autoGenerated: eventType === "APPLICATION_DEADLINE",
    title: "일정",
    startAt: new Date(startAt),
    endAt: new Date(startAt),
    allDay: false,
    location: "",
    onlineUrl: "",
    memo: "",
    reminderRules: [],
    createdAt: new Date("2026-08-01T00:00:00Z"),
    updatedAt: new Date("2026-08-01T00:00:00Z"),
  };
}

describe("칸반 컬럼 매핑", () => {
  it("백엔드 ApplicationStatus 8개가 모두 컬럼으로 1:1 매핑된다", () => {
    const columnStatuses = BACKEND_STATUSES.map(toApplicationStatusViewModel);

    expect(APPLICATION_KANBAN_COLUMNS).toEqual(columnStatuses);
  });

  it("카드를 현재 상태의 컬럼에 넣는다", () => {
    const columns = groupApplicationsByStatus([
      makeApplication("1", "작성중"),
      makeApplication("2", "면접"),
      makeApplication("3", "작성중"),
    ]);

    const byStatus = Object.fromEntries(
      columns.map((column) => [column.status, column.applications.map((item) => item.id)]),
    );

    expect(byStatus["작성중"]).toEqual(["1", "3"]);
    expect(byStatus["면접"]).toEqual(["2"]);
  });

  it("지원 건이 없는 상태도 빈 컬럼으로 남긴다", () => {
    const columns = groupApplicationsByStatus([makeApplication("1", "관심")]);

    expect(columns).toHaveLength(APPLICATION_KANBAN_COLUMNS.length);
    expect(columns.filter((column) => column.applications.length === 0)).toHaveLength(
      APPLICATION_KANBAN_COLUMNS.length - 1,
    );
  });
});

describe("toNextScheduleByApplicationId", () => {
  it("지원 건별로 가장 이른 일정 하나만 남긴다", () => {
    const nextSchedules = toNextScheduleByApplicationId([
      makeEvent("1", "FINAL_INTERVIEW", "2026-09-20T05:00:00Z"),
      makeEvent("1", "CODING_TEST", "2026-09-03T05:00:00Z"),
      makeEvent("2", "NCS_TEST", "2026-09-10T05:00:00Z"),
    ]);

    expect(nextSchedules["1"]).toMatchObject({ label: "코딩테스트" });
    expect(nextSchedules["2"]).toMatchObject({ label: "NCS 필기" });
  });

  it("마감 일정과 지원 건 없는 일정은 다음 일정으로 쓰지 않는다", () => {
    const nextSchedules = toNextScheduleByApplicationId([
      makeEvent("1", "APPLICATION_DEADLINE", "2026-09-01T05:00:00Z"),
      makeEvent("1", "FIRST_INTERVIEW", "2026-09-05T05:00:00Z"),
      makeEvent(null, "PERSONAL_PREPARATION", "2026-09-02T05:00:00Z"),
    ]);

    expect(nextSchedules["1"]).toMatchObject({ label: "1차 면접" });
    expect(Object.keys(nextSchedules)).toEqual(["1"]);
  });
});
