import { addDays, setTime } from "@/features/applications/date-utils";
import type { ApplicationListItem } from "@/features/applications/types";

const today = new Date();

export const applicationMockData: ApplicationListItem[] = [
  {
    id: "app-kb-2026-it",
    companyName: "KB국민은행",
    position: "IT 개발",
    recruitmentYear: 2026,
    season: "하반기",
    deadline: setTime(addDays(today, 2), 18, 0),
    status: "작성중",
    progress: 78,
    createdAt: addDays(today, -9),
  },
  {
    id: "app-shinhan-ict",
    companyName: "신한은행",
    position: "ICT",
    recruitmentYear: 2026,
    season: "하반기",
    deadline: setTime(addDays(today, 6), 23, 59),
    status: "작성중",
    progress: 20,
    createdAt: addDays(today, -4),
  },
  {
    id: "app-kakao-backend",
    companyName: "카카오",
    position: "백엔드",
    recruitmentYear: 2026,
    season: "수시",
    deadline: setTime(addDays(today, 10), 17, 0),
    status: "지원완료",
    progress: 100,
    createdAt: addDays(today, -18),
  },
  {
    id: "app-naver-platform",
    companyName: "네이버",
    position: "플랫폼 엔지니어",
    recruitmentYear: 2026,
    season: "상반기",
    deadline: setTime(addDays(today, 14), 15, 0),
    status: "면접",
    progress: 92,
    createdAt: addDays(today, -24),
  },
  {
    id: "app-line-server",
    companyName: "라인플러스",
    position: "서버 개발",
    recruitmentYear: 2026,
    season: "수시",
    deadline: setTime(addDays(today, -2), 18, 0),
    status: "서류",
    progress: 100,
    createdAt: addDays(today, -30),
  },
  {
    id: "app-toss-core",
    companyName: "토스",
    position: "Core Banking 개발",
    recruitmentYear: 2026,
    season: "수시",
    deadline: setTime(addDays(today, 1), 12, 0),
    status: "관심",
    progress: 10,
    createdAt: addDays(today, -1),
  },
  {
    id: "app-hyundai-data",
    companyName: "현대오토에버",
    position: "데이터 플랫폼",
    recruitmentYear: 2026,
    season: "하반기",
    deadline: setTime(addDays(today, 20), 18, 0),
    status: "최종합격",
    progress: 100,
    createdAt: addDays(today, -40),
  },
  {
    id: "app-coupang-infra",
    companyName: "쿠팡",
    position: "인프라 개발",
    recruitmentYear: 2026,
    season: "상반기",
    deadline: setTime(addDays(today, -8), 23, 59),
    status: "불합격",
    progress: 100,
    createdAt: addDays(today, -55),
  },
];
