package com.careerdock.application.service;

import com.careerdock.application.domain.Application;
import com.careerdock.calendar.domain.EventType;
import com.careerdock.calendar.domain.RecruitmentEvent;
import com.careerdock.calendar.domain.ReminderRule;
import com.careerdock.calendar.repository.RecruitmentEventRepository;
import com.careerdock.calendar.service.RecruitmentEventDeleteRequested;
import com.careerdock.calendar.service.RecruitmentEventUpsertRequested;
import java.time.Instant;
import java.util.List;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;

@Service
public class ApplicationDeadlineEventService {

    private final RecruitmentEventRepository eventRepository;
    private final ApplicationEventPublisher eventPublisher;

    public ApplicationDeadlineEventService(
            RecruitmentEventRepository eventRepository,
            ApplicationEventPublisher eventPublisher
    ) {
        this.eventRepository = eventRepository;
        this.eventPublisher = eventPublisher;
    }

    public void syncDeadlineEvent(Application application) {
        Instant deadlineAt = application.getDeadlineAt();
        if (deadlineAt == null) {
            deleteAutoDeadlineEvent(application);
            return;
        }

        RecruitmentEvent event = eventRepository
                .findByApplicationIdAndEventTypeAndAutoGeneratedTrue(
                        application.getId(), EventType.APPLICATION_DEADLINE)
                .map(existing -> {
                    existing.update(
                            application,
                            EventType.APPLICATION_DEADLINE,
                            deadlineTitle(application),
                            deadlineAt,
                            deadlineAt,
                            false,
                            null,
                            application.getApplicationSiteUrl(),
                            "지원관리 마감일에서 자동 생성된 일정입니다."
                    );
                    return existing;
                })
                .orElseGet(() -> {
                    RecruitmentEvent created = RecruitmentEvent.createApplicationGenerated(
                            application.getUser(),
                            application,
                            EventType.APPLICATION_DEADLINE,
                            deadlineTitle(application),
                            deadlineAt,
                            deadlineAt,
                            false,
                            null,
                            application.getApplicationSiteUrl(),
                            "지원관리 마감일에서 자동 생성된 일정입니다."
                    );
                    created.replaceReminderRules(ReminderRule.defaultsFor(created));
                    return eventRepository.save(created);
                });

        eventPublisher.publishEvent(new RecruitmentEventUpsertRequested(event.getId()));
    }

    public void deleteAutoGeneratedEvents(Application application) {
        List<RecruitmentEvent> events = eventRepository.findByApplicationIdAndAutoGeneratedTrue(application.getId());
        events.forEach(this::deleteAndPublish);
    }

    private void deleteAutoDeadlineEvent(Application application) {
        eventRepository.findByApplicationIdAndEventTypeAndAutoGeneratedTrue(
                        application.getId(), EventType.APPLICATION_DEADLINE)
                .ifPresent(this::deleteAndPublish);
    }

    private void deleteAndPublish(RecruitmentEvent event) {
        eventPublisher.publishEvent(
                new RecruitmentEventDeleteRequested(event.getId(), event.getUser().getId(), event.getGoogleEventId()));
        eventRepository.delete(event);
    }

    private String deadlineTitle(Application application) {
        return application.getCompany().getName() + " " + application.getPositionName() + " 지원 마감";
    }
}
