CREATE TABLE personal_infos (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    phone VARCHAR(30),
    address VARCHAR(300),
    school_name VARCHAR(150),
    major VARCHAR(150),
    double_major VARCHAR(150),
    minor VARCHAR(150),
    graduation_status VARCHAR(30),
    graduation_date DATE,
    gpa NUMERIC(4, 2),
    gpa_scale NUMERIC(4, 2),
    military_status VARCHAR(30),
    military_branch VARCHAR(50),
    military_rank VARCHAR(50),
    military_discharge_date DATE,
    career_summary VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_personal_infos_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_personal_infos_user_id UNIQUE (user_id),
    CONSTRAINT ck_personal_infos_gpa_range CHECK (gpa IS NULL OR (gpa >= 0 AND gpa <= 5.0)),
    CONSTRAINT ck_personal_infos_gpa_scale_range CHECK (gpa_scale IS NULL OR (gpa_scale > 0 AND gpa_scale <= 5.0)),
    CONSTRAINT ck_personal_infos_gpa_within_scale CHECK (gpa IS NULL OR gpa_scale IS NULL OR gpa <= gpa_scale)
);
