import { addDays } from "@/features/applications/date-utils";
import type {
  CredentialDetail,
  ExternalLink,
  MaterialFile,
  ProfileField,
  UserProfile,
} from "@/features/materials/types";

const today = new Date();

/**
 * 화면 확인용 예시 데이터.
 * 실제 개인정보와 실제 자격번호는 쓰지 않는다. 전화번호는 방송·예시용으로 비워둔
 * 010-0000-XXXX 대역을, 주소와 자격번호는 명백한 가상 값을 쓴다.
 */
export const userProfileMockData: UserProfile = {
  name: "홍길동",
  email: "hong.example@example.com",
  phone: "010-0000-0000",
  address: "서울특별시 예시구 예시로 000",
  school: "예시대학교",
  major: "컴퓨터공학과",
  doubleMajor: "",
  gpa: "3.082 / 4.5",
  militaryService: "군필 · 육군 병장 만기전역",
  careerSummary: "씨앤태크 ICT 인턴 6개월 · LOODI 서비스 운영",
};

export function toProfileFields(profile: UserProfile): ProfileField[] {
  return [
    { key: "name", label: "이름", value: profile.name, sensitive: false, copyable: true },
    { key: "email", label: "이메일", value: profile.email, sensitive: false, copyable: true },
    { key: "phone", label: "전화번호", value: profile.phone, sensitive: true, copyable: true },
    { key: "address", label: "주소", value: profile.address, sensitive: true, copyable: true },
    { key: "school", label: "학교", value: profile.school, sensitive: false, copyable: true },
    { key: "major", label: "주전공", value: profile.major, sensitive: false, copyable: true },
    {
      key: "doubleMajor",
      label: "복수전공",
      value: profile.doubleMajor,
      sensitive: false,
      copyable: true,
    },
    { key: "gpa", label: "학점", value: profile.gpa, sensitive: false, copyable: true },
    {
      key: "militaryService",
      label: "병역사항",
      value: profile.militaryService,
      sensitive: false,
      copyable: true,
    },
    {
      key: "careerSummary",
      label: "경력·인턴",
      value: profile.careerSummary,
      sensitive: false,
      copyable: true,
    },
  ];
}

export const credentialMockData: CredentialDetail[] = [
  {
    id: "credential-sqld",
    credentialType: "자격증",
    name: "SQLD",
    issuer: "한국데이터산업진흥원",
    acquiredAt: addDays(today, -400),
    credentialNumber: "SQLD-0000-EXAMPLE",
    score: "",
    grade: "합격",
    validFrom: addDays(today, -400),
    expiresAt: null,
    permanent: true,
    description:
      "데이터 모델링의 이해와 SQL 기본·활용, 최적화 기초를 검증하는 자격입니다. 관계형 데이터베이스 설계와 조회 성능을 다루는 직무에서 요구되는 경우가 많습니다.",
    usageMemo:
      "은행 IT 지원서의 자격사항에 기재합니다. 데이터베이스 직무역량 문항에서 인덱스 재설계 경험과 함께 근거로 씁니다.",
    studyMemo:
      "정규화와 조인 순서에서 계속 틀려서 실행 계획을 직접 뜯어보며 공부했습니다. 면접에서는 인덱스가 안 타던 쿼리를 고친 경험과 엮어서 말할 예정입니다.",
    evidenceFileName: "SQLD_합격증.pdf",
    referenceUrl: "https://www.dataq.or.kr",
    createdAt: addDays(today, -400),
    updatedAt: addDays(today, -30),
    usageHistories: [
      {
        id: "usage-sqld-kb",
        companyName: "KB국민은행",
        positionName: "IT 개발",
        applicationId: "app-kb-2026-it",
      },
      {
        id: "usage-sqld-shinhan",
        companyName: "신한은행",
        positionName: "ICT",
        applicationId: "app-shinhan-ict",
      },
    ],
  },
  {
    id: "credential-toeic",
    credentialType: "어학",
    name: "TOEIC",
    issuer: "한국TOEIC위원회",
    acquiredAt: addDays(today, -700),
    credentialNumber: "TOEIC-0000-EXAMPLE",
    score: "845",
    grade: "",
    validFrom: addDays(today, -700),
    expiresAt: addDays(today, 20),
    permanent: false,
    description:
      "영어 의사소통 능력을 측정하는 시험입니다. 성적은 응시일로부터 2년간 유효합니다.",
    usageMemo: "어학 항목에 기재합니다. 만료 전에 재응시해야 합니다.",
    studyMemo: "파트 7 시간 배분이 문제였습니다. 재응시 전에 실전 모의고사 위주로 준비할 계획입니다.",
    evidenceFileName: "TOEIC_성적표.pdf",
    referenceUrl: "https://exam.toeic.co.kr",
    createdAt: addDays(today, -700),
    updatedAt: addDays(today, -60),
    usageHistories: [
      {
        id: "usage-toeic-kb",
        companyName: "KB국민은행",
        positionName: "IT 개발",
        applicationId: "app-kb-2026-it",
      },
    ],
  },
  {
    id: "credential-opic",
    credentialType: "어학",
    name: "OPIc",
    issuer: "ACTFL",
    acquiredAt: addDays(today, -900),
    credentialNumber: "OPIC-0000-EXAMPLE",
    score: "",
    grade: "IM2",
    validFrom: addDays(today, -900),
    expiresAt: addDays(today, -170),
    permanent: false,
    description: "영어 말하기 능력을 평가하는 시험입니다. 성적은 2년간 유효합니다.",
    usageMemo: "만료되어 현재는 사용하지 않습니다. 재응시 후 갱신 예정입니다.",
    studyMemo: "",
    evidenceFileName: null,
    referenceUrl: "",
    createdAt: addDays(today, -900),
    updatedAt: addDays(today, -170),
    usageHistories: [],
  },
  {
    id: "credential-engineer-info",
    credentialType: "자격증",
    name: "정보처리기사",
    issuer: "한국산업인력공단",
    acquiredAt: addDays(today, -250),
    credentialNumber: "ENGINFO-0000-EXAMPLE",
    score: "",
    grade: "합격",
    validFrom: addDays(today, -250),
    expiresAt: null,
    permanent: true,
    description:
      "소프트웨어 개발 전반의 기초 지식을 검증하는 국가기술자격입니다. 요구사항 분석부터 테스트까지의 절차를 다룹니다.",
    usageMemo: "대부분의 IT 직무 지원서에 기본으로 기재합니다.",
    studyMemo: "실기 프로그래밍 언어 파트가 어려웠습니다. 기출 위주로 반복했습니다.",
    evidenceFileName: "정보처리기사_자격증.pdf",
    referenceUrl: "https://www.q-net.or.kr",
    createdAt: addDays(today, -250),
    updatedAt: addDays(today, -100),
    usageHistories: [
      {
        id: "usage-engineer-kakao",
        companyName: "카카오",
        positionName: "백엔드",
        applicationId: "app-kakao-backend",
      },
    ],
  },
  {
    id: "credential-adsp",
    credentialType: "자격증",
    name: "ADsP",
    issuer: "한국데이터산업진흥원",
    acquiredAt: addDays(today, -520),
    credentialNumber: "ADSP-0000-EXAMPLE",
    score: "",
    grade: "합격",
    validFrom: null,
    expiresAt: null,
    permanent: false,
    description: "데이터 분석 기초 지식을 검증하는 자격입니다.",
    usageMemo: "데이터 직무 지원 시 SQLD와 함께 기재합니다.",
    studyMemo: "",
    evidenceFileName: null,
    referenceUrl: "",
    createdAt: addDays(today, -520),
    updatedAt: addDays(today, -520),
    usageHistories: [],
  },
];

export const materialFileMockData: MaterialFile[] = [
  {
    id: "file-profile-photo-2026",
    fileName: "증명사진_2026.jpg",
    type: "증명사진",
    size: 842_120,
    createdAt: addDays(today, -18),
    isUsed: true,
    downloadUrl: "#",
  },
  {
    id: "file-backend-portfolio",
    fileName: "백엔드_포트폴리오.pdf",
    type: "포트폴리오",
    size: 5_382_144,
    createdAt: addDays(today, -12),
    isUsed: true,
    downloadUrl: "#",
  },
  {
    id: "file-transcript",
    fileName: "성적증명서.pdf",
    type: "성적증명서",
    size: 1_248_900,
    createdAt: addDays(today, -42),
    isUsed: false,
    downloadUrl: "#",
  },
  {
    id: "file-graduation-certificate",
    fileName: "졸업예정증명서.pdf",
    type: "졸업증명서",
    size: 1_012_340,
    createdAt: addDays(today, -35),
    isUsed: false,
    downloadUrl: "#",
  },
  {
    id: "file-engineer-info",
    fileName: "정보처리기사_자격증.pdf",
    type: "자격증",
    size: 734_820,
    createdAt: addDays(today, -28),
    isUsed: true,
    downloadUrl: "#",
  },
  {
    id: "file-project-reference",
    fileName: "LOODI_프로젝트_소개서.pdf",
    type: "기타",
    size: 2_761_500,
    createdAt: addDays(today, -8),
    isUsed: false,
    downloadUrl: "#",
  },
];

export const externalLinkMockData: ExternalLink[] = [
  {
    id: "link-github",
    type: "GitHub",
    title: "GitHub 프로필",
    url: "https://github.com/example-career",
    description: "백엔드 프로젝트와 알고리즘 풀이 저장소를 모아둔 프로필입니다.",
    createdAt: addDays(today, -120),
  },
  {
    id: "link-notion-portfolio",
    type: "Notion",
    title: "Notion 포트폴리오",
    url: "https://notion.so/example-career-portfolio",
    description: "프로젝트별 역할, 성과, 회고를 정리한 지원용 포트폴리오입니다.",
    createdAt: addDays(today, -95),
  },
  {
    id: "link-velog",
    type: "Velog",
    title: "기술 블로그",
    url: "https://velog.io/@example-career",
    description: "Spring Boot, PostgreSQL, Next.js 학습 기록을 정리합니다.",
    createdAt: addDays(today, -80),
  },
  {
    id: "link-portfolio-site",
    type: "Portfolio",
    title: "개인 포트폴리오 사이트",
    url: "https://portfolio.example.com",
    description: "대표 프로젝트와 이력 요약을 빠르게 확인할 수 있는 사이트입니다.",
    createdAt: addDays(today, -45),
  },
  {
    id: "link-linkedin",
    type: "LinkedIn",
    title: "LinkedIn",
    url: "https://www.linkedin.com/in/example-career",
    description: "공개 프로필과 경력 요약을 관리합니다.",
    createdAt: addDays(today, -30),
  },
];
