import { addDays, setTime } from "@/features/applications/date-utils";
import type { CalendarEvent } from "@/features/calendar/types";

const today = new Date();

export const calendarEventMockData: CalendarEvent[] = [
  {
    id: "event-kb-deadline",
    applicationId: "app-kb-2026-it",
    companyName: "KB국민은행",
    positionName: "IT 개발",
    eventType: "APPLICATION_DEADLINE",
    title: "[지원 마감] KB국민은행 · IT 개발",
    startAt: setTime(addDays(today, 4), 18, 0),
    endAt: setTime(addDays(today, 4), 18, 0),
    allDay: false,
    location: "",
    onlineUrl: "",
    memo: "자소서 최종 검토와 증빙 파일 첨부 상태를 확인합니다.",
    reminderRules: [
      { id: "kb-reminder-1", minutesBefore: 24 * 60, enabled: true, channel: "INTERNAL" },
      { id: "kb-reminder-2", minutesBefore: 3 * 60, enabled: true, channel: "INTERNAL" },
    ],
    syncStatus: "NOT_CONNECTED",
    createdAt: addDays(today, -8),
    updatedAt: addDays(today, -2),
  },
  {
    id: "event-kakao-coding",
    applicationId: "app-kakao-backend",
    companyName: "카카오",
    positionName: "백엔드",
    eventType: "CODING_TEST",
    title: "카카오 백엔드 코딩테스트",
    startAt: setTime(addDays(today, 7), 19, 0),
    endAt: setTime(addDays(today, 7), 21, 0),
    allDay: false,
    location: "온라인",
    onlineUrl: "https://programmers.co.kr",
    memo: "문제 풀이 환경과 신분 확인 절차를 미리 확인합니다.",
    reminderRules: [
      { id: "kakao-reminder-1", minutesBefore: 3 * 24 * 60, enabled: true, channel: "INTERNAL" },
    ],
    syncStatus: "NOT_CONNECTED",
    createdAt: addDays(today, -5),
    updatedAt: addDays(today, -1),
  },
  {
    id: "event-naver-interview",
    applicationId: "app-naver-platform",
    companyName: "네이버",
    positionName: "플랫폼 엔지니어",
    eventType: "FIRST_INTERVIEW",
    title: "네이버 플랫폼 엔지니어 1차 면접",
    startAt: setTime(addDays(today, 13), 14, 0),
    endAt: setTime(addDays(today, 13), 15, 0),
    allDay: false,
    location: "서울 강남구",
    onlineUrl: "",
    memo: "프로젝트 아키텍처와 장애 대응 경험을 복습합니다.",
    reminderRules: [
      { id: "naver-reminder-1", minutesBefore: 7 * 24 * 60, enabled: true, channel: "INTERNAL" },
      { id: "naver-reminder-2", minutesBefore: 24 * 60, enabled: true, channel: "INTERNAL" },
    ],
    syncStatus: "NOT_CONNECTED",
    createdAt: addDays(today, -4),
    updatedAt: addDays(today, -1),
  },
  {
    id: "event-personal-review",
    applicationId: null,
    companyName: "",
    positionName: "",
    eventType: "PERSONAL_PREPARATION",
    title: "자소서 최종 검토",
    startAt: setTime(addDays(today, 2), 20, 0),
    endAt: setTime(addDays(today, 2), 21, 0),
    allDay: false,
    location: "개인 일정",
    onlineUrl: "",
    memo: "제출 전 오탈자와 회사명 치환 오류를 확인합니다.",
    reminderRules: [
      { id: "personal-reminder-1", minutesBefore: 3 * 60, enabled: true, channel: "INTERNAL" },
    ],
    syncStatus: "NOT_CONNECTED",
    createdAt: addDays(today, -3),
    updatedAt: addDays(today, -3),
  },
];
