package com.careerdock.calendar.repository;

import com.careerdock.calendar.domain.RecruitmentEvent;
import com.careerdock.calendar.domain.SyncStatus;
import com.careerdock.calendar.domain.EventType;
import com.careerdock.dashboard.dto.DashboardApplicationCountProjection;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

public interface RecruitmentEventRepository
        extends JpaRepository<RecruitmentEvent, Long>, JpaSpecificationExecutor<RecruitmentEvent> {

    @EntityGraph(attributePaths = {"application", "application.company"})
    Optional<RecruitmentEvent> findByIdAndUserId(Long id, Long userId);

    @EntityGraph(attributePaths = {"application", "application.company"})
    Optional<RecruitmentEvent> findByApplicationIdAndEventTypeAndAutoGeneratedTrue(
            Long applicationId,
            EventType eventType
    );

    @EntityGraph(attributePaths = {"application", "application.company"})
    List<RecruitmentEvent> findByApplicationIdAndAutoGeneratedTrue(Long applicationId);

    /** 동기화 재시도 대상. pageable로 한 번에 재시도할 최대 건수를 제한한다. */
    List<RecruitmentEvent> findByUserIdAndSyncStatusIn(Long userId, List<SyncStatus> syncStatuses, Pageable pageable);

    /** Google Calendar를 처음 연결했을 때 과거 전체가 아니라 앞으로 남은 일정만 올린다. */
    List<RecruitmentEvent> findByUserIdAndSyncStatusInAndStartAtGreaterThanEqual(
            Long userId,
            List<SyncStatus> syncStatuses,
            Instant startAt,
            Pageable pageable
    );

    @Query("select e.syncStatus from RecruitmentEvent e where e.user.id = :userId")
    List<SyncStatus> findSyncStatusesByUserId(Long userId);

    long countByUserIdAndStartAtGreaterThanAndStartAtLessThanEqual(Long userId, Instant from, Instant to);

    @EntityGraph(attributePaths = {"application", "application.company"})
    @Query("""
            select e
            from RecruitmentEvent e
            where e.user.id = :userId
              and e.startAt > :from
            order by e.startAt asc, e.id asc
            """)
    List<RecruitmentEvent> findDashboardUpcomingEvents(Long userId, Instant from, Pageable pageable);

    @EntityGraph(attributePaths = {"application", "application.company"})
    @Query("""
            select e
            from RecruitmentEvent e
            where e.user.id = :userId
              and e.startAt >= :from
              and e.startAt < :to
            order by e.startAt asc, e.id asc
            """)
    List<RecruitmentEvent> findDashboardEventsBetween(Long userId, Instant from, Instant to, Pageable pageable);

    @Query("""
            select e.application.id as applicationId, count(e) as count
            from RecruitmentEvent e
            where e.user.id = :userId
              and e.application.id in :applicationIds
            group by e.application.id
            """)
    List<DashboardApplicationCountProjection> countDashboardEventsByApplicationIds(
            Long userId,
            List<Long> applicationIds
    );

    @EntityGraph(attributePaths = {"application", "application.company"})
    @Query("""
            select e
            from RecruitmentEvent e
            where e.startAt >= :from
              and e.startAt < :to
            order by e.startAt asc, e.id asc
            """)
    List<RecruitmentEvent> findNotificationStartTargets(Instant from, Instant to);
}
