spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///careerdock_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: false
